### ISSUE TITLE
Minilpaders

### ISSUE THREAD

**Issue by Archology** [djmango/BlackMarket2#11]
Your mod works, exept the miniloaders don't show up in the buy list, but I can craft these.
Mod list:
[asdfg.zip](https://github.com/djmango/BlackMarket2/files/4363503/asdfg.zip)

AlienSpaceScience_0.0.13
BeltUpgrader_1.0.3
Big_Brother_0.5.2
BlackMarket2_1.2.6
bobassembly_0.18.2
bobgreenhouse_0.18.0
boblibrary_0.18.0.
boblogistics_0.18.5
bobmodules_0.18.2
bobpower_0.18.4
bobtech_0.18.2.
DarkModules_0.5.1
DeepMine_0.5.4
DiscoScience_1.0.2
far-reach_0.18.0.
GatlingPulseLaser_1.18.1
leighzerscienceores_0.2.0
Long_Range_Radar_0.18.0
miniloader_1.10.8
necromant_0.18.7
NoCollision_0.0.5
Texugo_windgenerator_0.18.3
themightygugi_longreach_1.18.0.
UltimateBelts_0.18.2
Unlimited-Resources-18_1.1.0
Warehousing_0.3.0
windturbines_0.18.11

**Comment by djmango** [comment]
Looks like I am able to buy the [miniloaders](https://imgur.com/a/rgW3TH7). Try updating your mods and check if that works.

**Comment by Archology** [comment]
I try disable 1 by 1 my mods, maybe I find what cause the problem.

https://imgur.com/a/DknYF0z

**Comment by djmango** [comment]
Was there a launch error with bobs?

**Comment by Archology** [comment]
Nope, but I updated my prev. comment, all are fine now :)

**Comment by Archology** [comment]
Here is the images:

https://imgur.com/a/lkRPM9v

**Comment by djmango** [comment]
Alright cool, update if you find anything new!
