### ISSUE TITLE
Problem with Auto Buy

### ISSUE THREAD

**Issue by ladasno** [djmango/BlackMarket2#12]
When I queue to buy something and I've put a limit to a stack of an item when auto-buy happens instead of consuming one item's worth of units, it consumes the amount that requires to buy the amount that I've put in the auto-buy. :\

To put it simply, when the chest is full, instead of buying the amount needed to fill the chest up, it buys amount that I've set and wastes the units, which isn't really nice since it adds items to fill the chest.

Example.

I've 199 Iron plates in a slot.
I've set to auto-buy 200 plates per transaction
Every time the chest buys plates, it pays for 200 plates, but I only get 1 plate.

By the way, I've enabled the "Limit part of the inventory so it can't be filled by machines".

**Comment by djmango** [comment]
I am [unable to recreate this issue](https://i.imgur.com/2k7fPW7.png). What version are you running? Could you send me your mods-list and save?

**Comment by djmango** [comment]
closed for inactivity
