### ISSUE TITLE
Way too many items are set to cost 0, and other price problems

### ISSUE THREAD

**Issue by James-Fire** [djmango/BlackMarket2#14]
Bob's Ultimate Stack Inserters cost 0.
Bob's level 8 modules cost 0.
Bob's level 3 beacons cost 0.
All of Vortik's Deep Core chunks all cost 100, when they produce far more in ore. Some make 200 ore, some 100.
Electric engine units cost 0.
All the components from Space Extension cost 0.

This is not an exhaustive list. At the *very* least, these should not be defaulting to 0. Make them cost *something*.

And if you need something more robust to figure out costs of things, you can come look here https://github.com/James-Fire/Factorio-Tiberium/blob/Beta/Factorio-Tiberium/scripts/DynamicOreRecipes.lua

And talk to the guy that made it here https://discord.gg/Vt3hsrR

**Comment by djmango** [comment]
Does this behavior persist across versions?

**Comment by James-Fire** [comment]
I am already using the latest version. I downloaded and started this run less then 12 hrs ago, far below your 17 hr update.

**Comment by James-Fire** [comment]
Unless you want me to try an older version?

**Comment by djmango** [comment]
Yes please try an older version. I know I've tested Bob's on older versions, and the raw material value system hasn't changed since then so I'm trying to find the culprit. I've been meaning to rewrite that system in the mod anyway

**Comment by James-Fire** [comment]
I'll be able to do testing later.

How many versions should I try?

**Comment by djmango** [comment]
Just try 0.18.X along with the corresponding mod version if you can. Are you a modder yourself? I'm out of town for a few days so it's going to be at the weekend before I'm able to rewrite and fix this issue, so if you'd like you can submit a fix through a pull request. Thanks!

**Comment by James-Fire** [comment]
Yes, I very much am. If I can make myself familiar enough with the code, I might.

**Comment by djmango** [comment]
Alright cool, the code you'd be looking at starts at line 676 in control.lua. I'm not the one who wrote it so I don't have a complete grasp on it, it was written by the original mod creator who I have taken over for.

**Comment by James-Fire** [comment]
I have a feeling Transport Drones may be causing issues.

**Comment by djmango** [comment]
Just committed the fix for this, I have tested with Bob's and the prices are now all working. Expect the 2.0 release in a day or two

**Comment by James-Fire** [comment]
Yay, I'll let you know hot it goes once I have it.
