### ISSUE TITLE
[Suggestion] Better price scanning

### ISSUE THREAD

**Issue by Delnth** [djmango/BlackMarket2#16]
I play with Bob's/Angel's modpack along with other mods such helicopters, hovercraft and many more. These thing are very. Very. Insaly expensive to build and to research.

With Black Market you are one click away from just getting an helicopter, which is a few days of investment. More if you have mods that increase the aggressiveness and difficulty of the bitters, especially early game.

What I'm suggesting is to greatly lower ore sell prices, perhaps based on difficulty to get. It might be hard to code, however. I dunno. Here is how I was thinking it'd check the difficulty:

Research > Research cost > Ingredient cost > Availability of said ingredients

To elaborate, by default let's say one iron ore is worth 50u.
This price is unreasonable, especially early game. However, it might be if it has to go through a tedious process, such as the one in the modpack I'm playing: Mining deposit > Crushing the deposit > Sorting the crushed deposit > Yields one or two ore depending on which deposit it is.

This is an example of how complex it can be and how logical the prices should be. Currently I have 16k of lead ore, one unit of lead ore is worth 3,205u. That's 51,280,000u worth of money. No need to tell that with this amount of money, I could literally reach the endgame in an hour, and I'm barely touching the mid game right now.

That's my two cents, I just downloaded the mod and thought it was so damn cool I'd try to help improve it.

Edit: Also, a stock exchange rate would be incredible. The more you sell one item, the less gain you get out of it. Not sure if lowering the price due to low demand would be very balanced, so I'm not gonna suggest that.

**Comment by djmango** [comment]
The stock exchange rate is actually already implemented, through the dynamic price system. I plan on doing a full write up on all the core features of this mod after I release 2.0. The ease of buying your way to the end game is due to the default settings I programmed in, specifically the unknown prices and the unknown raw material prices. Do you think after I release 2.0 (a day or two) you could test with different settings and let me know what works best? That would be a big help and a huge improvement to the mod! Thanks so much!

**Comment by Delnth** [comment]
Yeah, I definitely could give it a shot and try it out. Looking forward to test those options. If it's not too much asking, I'd appreciate a short list of things I should be looking for, mainly those options you are talking about, the rest I can probably figure out. I already know what to check, my modpack contains really expensive stuff that require additional work and processing.

**Comment by djmango** [comment]
Great! The settings in question are the Resource price, and the Unknown price. If you could go into your .factorio directory, you could send your mod-list instead of copy-pasting it.

**Comment by djmango** [comment]
You can test it now if you'd like

**Comment by SGZ-TW-TY-20** [comment]
[mod-list.txt](https://github.com/djmango/BlackMarket2/files/5258404/mod-list.txt)
 Here's my bob's mod list if it is to help ? Darkstar.
