### ISSUE TITLE
Changing settings so that there are no price fluctuations set's all prices to 0

### ISSUE THREAD

**Issue by NewMellenia** [djmango/BlackMarket2#17]
When I change the settings that affect price change to 0, all prices are set to 0 and i'm no sure of the cause. I am playing modded however I have a lot of mods and there are too many to list. I'm not sure what is causing the issue but i hope it gets fixed as the price fluctuations are a bit annoing

**Comment by djmango** [comment]
Which specific setting are you changing?

**Comment by NewMellenia** [comment]
dynamic influence on both item and enegery. I set them to 0 assuming that meant that there would be 0 influence on pricing and thus pricing would remain the same

**Comment by djmango** [comment]
Alright I've added and tested the code to solve this problem. I've also added a checkbox to disable or enable dynamic pricing altogether, to make this process easier. I will release the update within a day or two, with my 2.0 rewrite update
