### ISSUE TITLE
After the update, the game now crashes on load

### ISSUE THREAD

**Issue by NewMellenia** [djmango/BlackMarket2#19]
when i load he game is get this
the game then crashes and returns to main menu
![error](https://user-images.githubusercontent.com/70609277/92292195-884cac80-eee1-11ea-9bc1-b921a31faaf6.jpg)

**Comment by djmango** [comment]
Can you let me know which mods you're using so I can recreate the issue? Just send the modslist if that's easier for you.

**Comment by NewMellenia** [comment]
i'm not sure as to how to create a mod list so i just copied the folder and uploaded it to google drive as it is too big to upload in a comment, all mods in the folder are active 

https://drive.google.com/file/d/1qurYNd_VTg-5-3XyP9UkQg_834wKPJLz/view?usp=sharing

**Comment by djmango** [comment]
Can you test with the update I just released?

**Comment by NewMellenia** [comment]
it now seems to work!

**Comment by djmango** [comment]
Great!
