### ISSUE TITLE
Error with Gold Mining mod

### ISSUE THREAD

**Issue by Mechaniling** [djmango/BlackMarket2#2]
With the Gold Mining mod running along side this one, Black Market 2 fails to load. Below is the message that I end up with when attempting to run them together.

![Error_with_gold_mining_mod](https://user-images.githubusercontent.com/55765388/65547609-d0004100-dee7-11e9-8799-0dd128062e4a.png)

I have no idea what I'm looking at here, just reporting an error/bug where you requested we put 'em.

**Comment by djmango** [comment]
Investigated the bug, thanks for the report. Newest version (1.2.4) fixes it
