### ISSUE TITLE
How do I reset my money?

### ISSUE THREAD

**Issue by lettuce33** [djmango/BlackMarket2#21]
I think I broke my money.
<img width="190" alt="Screen Shot 2020-09-06 at 1 50 14 PM" src="https://user-images.githubusercontent.com/70856889/92331939-0d51d600-f048-11ea-8a04-ea45fdfbfaae.png">

**Comment by djmango** [comment]
Could you walk me through how this occurred? If you'd like to cheat your money back in you can with the command
```
/c remote.call("market", "credits", 50)
```

you can replace 50 with however many credits you'd like. beware this is cheating and will disable achievements in your save.

**Comment by lettuce33** [comment]
So my friend sold some crushed stone from Angel's Refining. I'm not sure what else he did, but I'm pretty sure that's the main cause to it.

**Comment by djmango** [comment]
I'll release an update with a fix for this tonight, thanks for bringing it to my attention

**Comment by Tosarius** [comment]
Happened to me, too. Sold some crushed stone.

**Comment by NingWen-In-Hub** [comment]
> Happened to me, too. Sold some crushed stone.

Happened to me, too. I sold some thing from PyMod  :(
