### ISSUE TITLE
Erro in start up

### ISSUE THREAD

**Issue by Fatag** [djmango/BlackMarket2#24]
![Screenshot_46](https://user-images.githubusercontent.com/8174363/94603940-55da6900-026d-11eb-835c-7987561b0d19.png)

this error is shown when starting the game

**Comment by djmango** [comment]
what mods?

**Comment by Fatag** [comment]
- AAI MODS (aai-programmable-structures / aai-programmable-vehicles / aai-signal-transmission / aai-signals / aai-vehicles-chaingunner / aai-vehicles-flame-tank / aai-vehicles-flame-tumbler / aai-vehicles-hauler /aai-vehicles-laser-tank / aai-vehicles-miner / aai-vehicles-warden / ai-zones / aai-industry)
- Additional Turret
- Advanced Solar
-  Air Filtering
- Aircraft
- Aircraft Drones
- Alien Biomes
- Angel's Mod (angelsaddons-oresilos / angelsaddons-petrotrain / angelsaddons-pressuretanks / angelsaddons-smeltingtrain / angelsaddons-warehouses / angelsbioprocessing / angelsindustries / angelspetrochem / angelsrefining / angelssmelting)
- Beautiful Bridge Railway
- Belt Sorter
- Big Bags
- Big Drill
- Big Brother
- Bio Industries
- BlackMarket2
 - Bob's Mod (bobassembly / bobelectronics / bobenemies / bobequipment / bobgreenhouse / bobinserters / boblibrary / boblogistics / bobmining / bobmodules / bobores / bobplates / bobpower / bobrevamp / bobtech / bobvehicleequipment / bobwarfare)
- Bottleneck
- Bullet Trails
- Construction Drones
- Crafting Speed Research
- Orbital Solar Power
- Deadlock Beltboxes Loaders
- Deep Storage Unit
- Deep Mine
- Disco Science
- Double Furnace
- Dragon Industries
- Electric Furnaces
- Electric Train
- EvoGUI
- Factorissimo2
- Flare Stack
- flib
- Fluid Memory Storage
- FNEI
- Force Fields2
- God Module
- Helmod
- Informatron
- Instant Robot Charging
- Item Teleportation
- Jetpack
- KS Power
- Load Furn
- Loader Redux
- logistic-memory-units
- LogisticTrainNetwork
- long-reach
- LSlib
- manual-inventory-sort
- miniloader
- Mining-Space-Industries
- Mobile Factory (Mobile_Factory / Mobile_Factory-Erya / Mobile_Factory-Jets / Mobile_Factory_Graphics)
- Nanobots
- nixie-tubes
- NoCraftingTime
- No_Bots_Please
- OmegaDrill
- OpteraLib
- Orbital Ion Cannon
- Power Armor MK3
- PowerAndArmor
- Pylons
- qol_research
- railloader
- Raven
- Reinforced-Walls
- Robocharger
- robotMiningSite
- robot_attrition
- rso-mod
- Side Inserters
- skan-advanced-solar
- skipresearch
- SmallRobots
- some-corpsemarker
- SpaceMod
- spidertron-extended
- spidertron-logistics
- SSP
- stargate
- stdlib
- super-logistics
- Teleporters
- TeleportProviderChest
- TheFatController
- TimeTools
- Turret-Shields
- UltimateBelts
- upgrade-planner-nex
- VehicleSnap
- vtk-deep-core-mining
- walls-block-spitters"
- Warehousing
- WaterWell
- WhereIsMyBody
- WideChests
- YARM
- yi_engines
- yi_railway
- Yi_Tech_Tree
- Yuok
- z_yira_american
- z_yira_UP
- z_yira_yuokirails",

**Comment by Fatag** [comment]
I removed the mods

- Bucket Wheel Excavators
- EvoGUI
- Helmod
- Omega Drill
- Pylons
- Robot Mining Site
- Skydragon's Advanced Solar
- The fat controller
- where my body

removing these mods I can open the game with black market 2

**Comment by djmango** [comment]
do you think you could narrow it down further? that's a lot of mods for me to debug

**Comment by kurosnow** [comment]
Judging by the error (accumulator.nextupgrade) it'd be an incompatibility with something that adds accumulators, which of those, I'd say advanced solar would be the only one.

**Comment by djmango** [comment]
alright thanks for the clarification, I'll look into it when I have some
time

**Comment by djmango** [comment]
That mod is only for 0.18, so it really shouldn't be used with BlackMarket2. Thanks for the help!
