### ISSUE TITLE
Error placing Buy Chest.

### ISSUE THREAD

**Issue by SkornClaw** [djmango/BlackMarket2#26]
The mod Black Market 2 (2.0.3) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event BlackMarket2::on_built_entity (ID 6)
__BlackMarket2__/control.lua:2053: attempt to index field 'coal' (a nil value)
stack traceback:
	__BlackMarket2__/control.lua:2053: in function <__BlackMarket2__/control.lua:2009>

This error happens when U place the buy chest.

Error does not seem to be related to Krastorio2.

[AndrewBramModSave.zip](https://github.com/djmango/BlackMarket2/files/5360363/AndrewBramModSave.zip)

[AndrewBramModSave 2.zip](https://github.com/djmango/BlackMarket2/files/5360362/AndrewBramModSave.2.zip)

Image is of a mod save I had where Black Market 2 was previously working.

![image](https://user-images.githubusercontent.com/13258973/95666524-17239900-0b20-11eb-851c-93d40ed260b2.png)

Just to add to the fun and confusion, I just synced my mod settings to save save where it did work, and it did not let me place the chest after the sync (Which to me suggests that its something happening during map creation).

Also with my Current mod loadout, I am capable of loading my save without Syncing and the Black Market 2 mod will work with all of the new mods installed.

[Bram Solo Mods.zip](https://github.com/djmango/BlackMarket2/files/5360393/Bram.Solo.Mods.zip)
This is the save where it worked (Not that its relevant, just in case its needed)

**Comment by djmango** [comment]
I am unable to recreate this issue. I'm releasing an update with something that should resolve this regardless, but I can't verify as even with your saves and mods I can't recreate the issue. Make sure you are on latest stable factorio and have your mods updated

**Comment by SkornClaw** [comment]
I really hope what you release fixes it because I really miss using this mod and for the life of me couldn't figure out why, or where the conflict comes. You also synched the mods start-up settings correct?

**Comment by djmango** [comment]
yes I did, patch should be up tonight or tomorrow night

**Comment by SkornClaw** [comment]
Issue is still persistent for me even with my current save.

[AndrewBramModSave 2.zip](https://github.com/djmango/BlackMarket2/files/5369284/AndrewBramModSave.2.zip)

If your not having the issue, would you perhaps be able to load into the save, make your own save and send it back to see if problem disappears (Or leave chest placed so when i load back in we can see if it throws a different error)
