### ISSUE TITLE
Index error when using "Only enable items researched"

### ISSUE THREAD

**Issue by Eylrid** [djmango/BlackMarket2#34]
Factorio version: 1.1.48
BlackMarket2 version: 2.1.0

Steps to reproduce:
1. Set "Only enable items researched" to true in mod settings
2. Start new game
3. Use editor to get a Trading tank (buy)
4. Place tank

Results in the following error:

The mod Black Market 2 (2.1.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event BlackMarket2::on_built_entity (ID 6)
__BlackMarket2__/control.lua:2071: attempt to index field 'crude-oil' (a nil value)
stack traceback:
	__BlackMarket2__/control.lua:2071: in function <__BlackMarket2__/control.lua:2020>

The error doesn't happen with "Only enable items researched" disabled.

**Comment by AshPrinny** [comment]
I have the same issue only for me it throws back the Index field "coal" (a nil value) option

It's because raw resources don't have a RESEARCH attached to them that unlocks them so it never unlocks them to buy either causing a deadfall trap in the code of the program.

**Comment by djmango** [comment]
I'm unable to recreate the issue. Are you using additional mods? Are you using a different version of Factorio? What do you mean by use editor, the scenario editor or is this something else?

**Comment by Eylrid** [comment]
> Are you using additional mods?

No, no additional mods.

> Are you using a different version of Factorio?

The version I used is listed in my first comment.

I also tried it in the latest version of Factorio, 1.1.59 and it still happens.

> What do you mean by use editor, the scenario editor or is this something else?

I'm talking about the in game editor that you get by typing `/editor` in the console. You can also get the same problem in the regular game without using the editor. The editor is just the quickest way to get to the problem.

**Comment by Eylrid** [comment]
If you want I can take a video showing what I do to get the problem.

**Comment by djmango** [comment]
> If you want I can take a video showing what I do to get the problem.

Yeah that would be great thanks

**Comment by Eylrid** [comment]
https://youtu.be/qKIki9d0Dd8

**Comment by djmango** [comment]
Yeah that would be great thanks

From: Eylrid ***@***.***>
Date: Monday, June 6, 2022 at 1:34 AM
To: djmango/BlackMarket2 ***@***.***>
Cc: Sulaiman Ghori ***@***.***>, Assign ***@***.***>
Subject: Re: [djmango/BlackMarket2] Index error when using "Only enable items researched" (Issue #34)

If you want I can take a video showing what I do to get the problem.
