### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by WizardKT** [djmango/BlackMarket2#41]
Error while running event BlackMarket2::on_built_entity (ID 6)
__BlackMarket2__/control.lua:2071: attempt to index field 'crude-oil' (a nil value)
stack traceback:
	__BlackMarket2__/control.lua:2071: in function <__BlackMarket2__/control.lua:2020>****

**Comment by djmango** [comment]
Could you send your ‘mods-list.json’?
________________________________
From: WizardKT ***@***.***>
Sent: Saturday, February 25, 2023 4:00:11 PM
To: djmango/BlackMarket2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [djmango/BlackMarket2] Error (Issue #41)


Error while running event BlackMarket2::on_built_entity (ID 6)
BlackMarket2/control.lua:2071: attempt to index field 'crude-oil' (a nil value)
stack traceback:
BlackMarket2/control.lua:2071: in function <BlackMarket2/control.lua:2020>****
