### ISSUE TITLE
The problem with prices

### ISSUE THREAD

**Issue by MaxxDnepr1** [djmango/BlackMarket2#42]
Rocket fuel used to cost 150,000 per unit and then suddenly became worth 16 What could be the reason?
All my sales are down and now I don't know how to fix it
![fact](https://user-images.githubusercontent.com/39877726/224972937-cec2ba10-624c-4a70-904f-479beba85083.PNG)

**Comment by MaxxDnepr1** [comment]
I looked at all the settings of the 
![fac2](https://user-images.githubusercontent.com/39877726/224974136-9fb86a44-cbbe-4817-b204-83e8eeeaaa7e.PNG)
mod and turned off these functions a long time ago

**Comment by djmango** [comment]
Hmm what’s your mods list?
________________________________

**Comment by MaxxDnepr1** [comment]
![11](https://user-images.githubusercontent.com/39877726/224975384-030f561d-1458-4276-b4bc-2cf63640f1bb.PNG)
![22](https://user-images.githubusercontent.com/39877726/224975389-8e1d58a2-2ed0-4199-8831-56fddbf0b8d8.PNG)
![33](https://user-images.githubusercontent.com/39877726/224975392-d158bdc4-f188-4ca6-b5ee-5fcde3db66d0.PNG)
![44](https://user-images.githubusercontent.com/39877726/224975394-e5ee3016-2190-4988-a8a4-563678d50f75.PNG)

**Comment by MaxxDnepr1** [comment]
I play with these mods a lot of time including Market 2 but this error appeared a day ago

**Comment by djmango** [comment]
Historical price – just change all instances of 11824

From: MaxxDnepr1 ***@***.***>
Date: Tuesday, March 14, 2023 at 8:04 PM
To: djmango/BlackMarket2 ***@***.***>
Cc: Sulaiman Ghori ***@***.***>, Comment ***@***.***>
Subject: Re: [djmango/BlackMarket2] The problem with prices (Issue #42)

I need to change the price here for the product I want and it will be fine, but I do not understand what these other numbers (11824 is the price in the game and need 160000)
[666]<https://user-images.githubusercontent.com/39877726/225110622-3ec138f6-c607-491d-a033-d86db7d574d8.PNG>

**Comment by MaxxDnepr1** [comment]
So also has not changed, is it possible to add to the mod itself string that I could change the price is in the game as to these resources?
![image](https://user-images.githubusercontent.com/39877726/225257914-58c67321-0dbd-4b70-ba38-e264cd281d28.png)

**Comment by djmango** [comment]
Yeah there’s a lua file I believe, you could do that and submit a PR for the option, would be awesome!

From: MaxxDnepr1 ***@***.***>
Date: Wednesday, March 15, 2023 at 9:57 AM
To: djmango/BlackMarket2 ***@***.***>
Cc: Sulaiman Ghori ***@***.***>, Comment ***@***.***>
Subject: Re: [djmango/BlackMarket2] The problem with prices (Issue #42)

So also has not changed, is it possible to add to the mod itself string that I could change the price is in the game as to these resources?
[image]<https://user-images.githubusercontent.com/39877726/225257914-58c67321-0dbd-4b70-ba38-e264cd281d28.png>

**Comment by MaxxDnepr1** [comment]
Looked at your code and did as you did, but the game is like this
![image](https://user-images.githubusercontent.com/39877726/225275617-99b52af2-7330-4d77-80a6-ff28d46c3adb.png)

**Comment by MaxxDnepr1** [comment]
I added a couple of lines to the code and now everything works

**Comment by djmango** [comment]
> I added a couple of lines to the code and now everything works

Thats awesome! Great to hear you solved it. Could you post the lines so others could see your solution too?

**Comment by MaxxDnepr1** [comment]
I do not understand how to do something on this forum, but I can show you in screenshots what I have added
![image](https://user-images.githubusercontent.com/39877726/225289186-8f34aa42-afd4-4651-9135-13eb246fae7c.png)
![image](https://user-images.githubusercontent.com/39877726/225289412-abe3a2d1-8335-4c5c-be3d-7cdd667a1ad0.png)
