### ISSUE TITLE
Support for PyAlienLifes many items

### ISSUE THREAD

**Issue by DodoCooker** [djmango/BlackMarket2#47]
Py has over 1000 items in a single tab so BlackMarket cuts off at 999 items - could you extend it to 9999 items? I've done the attached changes on my local version in the 1.1 version for a few months and it worked without hickups (patch is made with the current 2.0 version). 
[blackmarketpy.patch](https://github.com/user-attachments/files/17515815/blackmarketpy.patch)

**Comment by djmango** [comment]
Could you submit this as a PR? Happy to merge! Thanks for bringing this

**Comment by DodoCooker** [comment]
https://github.com/djmango/BlackMarket2/pull/49
