### ISSUE TITLE
Error v2.2.3 windows

### ISSUE THREAD

**Issue by dispod** [djmango/BlackMarket2#48]
![Screenshot_1](https://github.com/user-attachments/assets/08ca2093-6111-4efb-aa4c-9c203716b717)

**Comment by djmango** [comment]
@lmst2 looks like for some it is causing an issue? unclear why for some and not others

**Comment by dispod** [comment]
fix error in version 2.2.4
https://mods.factorio.com/mod/BlackMarket2_SpaceAgeFix/changelog

**Comment by lmst2** [comment]
> @lmst2 looks like for some it is causing an issue? unclear why for some and not others

my bad, it was from my uploaded mod, I linked to your repository in the souse code link before. 
that mod was uploaded before you merge the pr. but can't find a button to delete it, so I just leave it there.

**Comment by djmango** [comment]
Ah, so no problem in this version?

**Comment by lmst2** [comment]
> Ah, so no problem in this version?

yeah, no problem
