### ISSUE TITLE
Black market 2 (2.2.5) caused a non-recoverable error

### ISSUE THREAD

**Issue by petergao96** [djmango/BlackMarket2#53]
Received this crash issue after today's update.

Error while running event BlackMarket2::on_tick (ID 0)
_ _BlackMarket2_ _/control.lua:1508: attempt to perform arithmetic on field '?' (a nil value)
stack traceback:
_ _BlackMarket2_ _/control.lua:1508: in function 'buy_trader'
_ _BlackMarket2_ _/control.lua:2356: in function
<_ _BlackMarket2_ _/control.lua:2202>

**Comment by petergao96** [comment]
![image](https://github.com/user-attachments/assets/f631cdea-c07b-4ddb-8011-8ac1d18e67ca)

My mod list. This was working before the update though.

**Comment by nolialsea** [comment]
The workaround is to replace all the market chests to avoid them having a nil value for the quality.

**Comment by lmst2** [comment]
that was fixed in the new release
