### ISSUE TITLE
Crash when selling item with quality above Legendary

### ISSUE THREAD

**Issue by LoganDark** [djmango/BlackMarket2#55]
https://mods.factorio.com/mod/BlackMarket2/discussion/672825e69a7e098a2efc61f3

When a mod adds any quality levels above legendary, you can't sell anything with those quality levels because it throws an unrecoverable error

You also can't buy anything with those quality levels either

**Comment by djmango** [comment]
Very useful yes! Thanks

**Comment by LoganDark** [comment]
```
The mod Black Market 2 (2.2.6) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event BlackMarket2::on_gui_click (ID 1)
__BlackMarket2__/control.lua:1412: attempt to perform arithmetic on local 'quality_multiplier' (a nil value)
stack traceback:
	__BlackMarket2__/control.lua:1412: in function 'sell_trader'
	__BlackMarket2__/control.lua:2677: in function <__BlackMarket2__/control.lua:2459>
```

(it happens also when the sell happens automatically)

**Comment by LoganDark** [comment]
actually maybe I could open a pull request for this later

**Comment by djmango** [comment]
That would be amazing!

**Comment by lmst2** [comment]
i didn't realize we could have a quality higher than lengendary lol.

for the names i use here, the official api that returns item's quality only give me the str name of it. so it is hard if i don't use a dict to map those names into numbers. if they just return a number then no need to do this mapping. if you see other better api, then you can mention me later.

**Comment by LoganDark** [comment]
> i didn't realize we could have a quality higher than lengendary lol.
> 
> for the names i use here, the official api that returns item's quality only give me the str name of it. so it is hard if i don't use a dict to map those names into numbers. if they just return a number then no need to do this mapping. if you see other better api, then you can mention me later.

Qualities are integers internally, so whatever API is turning them to strings is wrong, since you have no way of figuring out what the names mean without hardcoding them, which results in issues like this one. I'll take a look and see if there's any way to get the number

**Comment by LoganDark** [comment]
[`prototypes`](https://lua-api.factorio.com/latest/classes/LuaPrototypes.html)[`.quality`](https://lua-api.factorio.com/latest/classes/LuaPrototypes.html#quality)`[name]` gets the [`LuaQualityPrototype`](https://lua-api.factorio.com/latest/classes/LuaQualityPrototype.html) for a given `name`. Then you can get the [`level`](https://lua-api.factorio.com/latest/classes/LuaQualityPrototype.html#level) of the quality. This will be easy, I'll open a PR soon

**Comment by lmst2** [comment]
> [`prototypes`](https://lua-api.factorio.com/latest/classes/LuaPrototypes.html)[`.quality`](https://lua-api.factorio.com/latest/classes/LuaPrototypes.html#quality)`[name]` gets the [`LuaQualityPrototype`](https://lua-api.factorio.com/latest/classes/LuaQualityPrototype.html) for a given `name`. Then you can get the [`level`](https://lua-api.factorio.com/latest/classes/LuaQualityPrototype.html#level) of the quality. This will be easy, I'll open a PR soon

oh yeah this solved both buying and selling, just replace the hardcoded map with this one and little tweaks to the functions it will work

**Comment by LoganDark** [comment]
yep that's what I'm doing, I'll open a PR soon

**Comment by djmango** [comment]
Released!
