### ISSUE TITLE
crash bug

### ISSUE THREAD

**Issue by twig1233** [djmango/BlackMarket2#58]
![image](https://github.com/user-attachments/assets/973528b0-1c95-4e89-8244-9171b30b88db)

**Comment by TomNookman** [comment]
here is the code
`The mod Black Market 2 (2.2.8) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event BlackMarket2::on_tick (ID 0)
Invalid QualityID: expected LuaQualityPrototype or string.
stack traceback:
	[C]: in function 'insert'
	__BlackMarket2__/control.lua:1548: in function 'buy_trader'
	__BlackMarket2__/control.lua:2386: in function <__BlackMarket2__/control.lua:2232> `

if you need anything from me I can grab it

I get the error message around 45 seconds after loading my save after updating the mod

**Comment by LoganDark** [comment]
just fixed this, opening a PR now
