### ISSUE TITLE
Crash on placing buy chest

### ISSUE THREAD

**Issue by TehChosenOne** [djmango/BlackMarket2#62]
The mod Black Market 2 (2.2.10) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event BlackMarket2::on_tick (ID 0)
Index out of range.
stack traceback:
[C]: in function 'newindex'
__BlackMarket2/control.lua:551: in function 'add_order'
BlackMarket2/control.lua:558: in function 'update_menu_trader'
BlackMarket2/control.lua:2309: in function <BlackMarket2/control.lua:2242>

Notes:
- Happens by opening the buy chest
- No other mods, fresh start + cheat mode to get the chest
- Only the chest, on accumulator and tank no crashes
- I dont have the space age DLC
- Tested clean reinstall of mod + confirmed crash with friend playing in multiplayer (also doesnt have DLC)
- More people have same issue on factorio mod page discussions

**Comment by djmango** [comment]
@LoganDark @lmst2 any ideas?

**Comment by lmst2** [comment]
i think add_order() trying to add item in the quality dropdown, and the quality level is used as index. and I believe that index should starts with 1 but quality level starts with 0, therefore need to shift the quality level by 1. me prepairing for exam, lets see so if LoganDark can do it.

**Comment by LoganDark** [comment]
@djmango I think if someone doesn't have the space age DLC there might be literally no qualities which might be what's causing the crash, I'll take a look

**Comment by LoganDark** [comment]
Yep looks like without space age there are literally no qualities
