### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by The-Master27** [djmango/BlackMarket2#7]
What mod settings do I need to set to stop prices fluctuating

**Comment by djmango** [comment]
[This pull request](https://github.com/djmango/BlackMarket2/pull/4) details the settings you can and can't change. I believe that you are looking for the `BM2-dynamic_` settings, line 237-283 in `settings.lua`
![image](https://user-images.githubusercontent.com/28496988/73183305-96835080-40e8-11ea-9481-3248d05a457e.png)
