### ISSUE TITLE
General price multiplier

### ISSUE THREAD

**Issue by Tosarius** [djmango/BlackMarket2#9]
It would be nice to have a general price multiplier for the final prices.
For example:
final price = calculated price x multiplier

good A = 100; multiplier = 2 => final price good A = 200

**Comment by djmango** [comment]
This is available for items through the [resource price mod setting.](https://i.imgur.com/CIkmdXe.png)

**Comment by Tosarius** [comment]
Since it's not strictly a multiplier, how do you use it?
Is it like 100 = 100% base price? so 150 would be like 50% more expensive?

**Comment by djmango** [comment]
> Since it's not strictly a multiplier, how do you use it?
> Is it like 100 = 100% base price? so 150 would be like 50% more expensive?

I believe that's how it works, however this feature was developed by the previous maintainer, not me, so I'm not 100% sure.

I'm out of town at the moment but expect a dedicated 'Price Multiplyer' within the next week, I'll add it when I get back home.

**Comment by djmango** [comment]
Good news, finished the price multiplyer, it is now in the latest release :+1:
It is the first setting in the mod settings page
